### ISSUE TITLE
Integrating image picker widget in Survey Editor issues

### ISSUE THREAD

**Issue by maria-negrea** [surveyjs/widgets#30]
I am trying to integrate the image picker widget in Survey Editor. So far, I've encountered the following issues:
- in order for the image picker to be rendered, the items of the choices property must be defined by Value and ImageLink(instead of Text)
![git](https://user-images.githubusercontent.com/6886765/35632974-d5ce2c84-06b0-11e8-8246-b1731376c6a7.JPG)
 -there is no control over images size (huge images will be displayed in scrollable containers instead of being resized to fit the available area)

Do you have any suggestions for solving this issues?

**Comment by tsv2013** [comment]
We need to introduce a custom property editor for image picker choices. This editor should be added to the widgets library.

**Comment by maria-negrea** [comment]
Also, it would be a nice feature to have the option to upload a file instead of specifying its URL.

**Comment by tsv2013** [comment]
@maria-negrea Thank you for the suggestion. We'll discuss it with the team.

**Comment by SamMousa** [comment]
Regarding image upload, one solution would be to store the image as a data URI inside the JSON.

It'll increase the survey JSON size but does not require separate functionality to upload images. From a development perspective it'll also be easier since there's loose coupling between the image picker and SurveyJS. 
(Ie any image picker that returns a URL for the selected image, no matter if it's a data URI or a result URI of an upload will work).

**Comment by dmitrykurmanov** [comment]
Now image picker is a part of the SurveyJS library and fully supported by the editor. Please look at the example: https://surveyjs.io/Examples/Library/?id=questiontype-imagepicker&platform=jQuery&theme=default
