### ISSUE TITLE
Request: Extend Select2 to use Remote Data

### ISSUE THREAD

**Issue by wollerman** [surveyjs/widgets#31]
I know there is the option of `choicesByUrl` for dropdowns that preloads all options. However, I am trying to setup a dropdown that acts like a search. I.e. the results are not loaded until the user starts typing. When a user types a query is sent and the results may change. 

It seems like Select2 supports this through their [Remote Data functionality.](https://select2.org/data-sources/ajax) Is it possible to do this via `choicesByUrl`? Or extend Select2 to use `ajax` keyword?

Thanks!

**Comment by dmitrykurmanov** [comment]
Hello! Thank you for the issue. This is really more general task than just adding select2 ajax functionallity. Because of each custom widget can contains more options and different params combinations. Currently we have no such a functionality. We will think how to implement it the proper way.

At this moment we can suggest you a workaround - copy/paste the select2 widget code into your application and write necessary code for your custom scenario. We'll help you in case of any troubles.

**Comment by tsv2013** [comment]
We need to have general solution for such a cases - https://github.com/surveyjs/widgets/issues/32 - Custom config of 3d party libraries for custom widgets

**Comment by wollerman** [comment]
A general solution would definitely be ideal. I realized after my original query that select2 ajax would require more than a single field being exposed.

In terms of this particular widget integration, I am also trying to determine what the best way to provide authorization for the http request would be. That idea breaks the static-ness of a surveyjs json definition because now it depends on a particular session. Maybe the `SurveyJS.Model` has another parameter for `authorizations` or `tokens` to be used by the widgets? Then the widget could use the information from there? Definitely a half baked idea. 

Thanks for the quick responses!

**Comment by tsv2013** [comment]
@wollerman If we are talking about authorization for the choicesByUrl option, you can check this ticket - https://surveyjs.answerdesk.io/ticket/details/T405 - probably this helps
