### ISSUE TITLE
Widget in SurveyJS Vue

### ISSUE THREAD

**Issue by gongon2dotcom** [surveyjs/widgets#51]
How to use custom widgets in Vue SurveyJS ????

Thanks.

**Comment by gongon2dotcom** [comment]
Thanks @tsv2013. I had already seen the example on SurveyJS website. I'm developing in Vue Spa 'mode' so i need to import widgets like components and then use them in my app.
I wrote something like this : 

`
<script>
import Vue from 'vue'
import * as SurveyVue from 'survey-vue'
**import * as SurveyWidget from 'surveyjs-widgets'**
import surveyJson from '../../static/survey.json'
import axios from 'axios'

var Survey = SurveyVue.Survey
Survey.cssType = "bootstrap"

**Vue.use(SurveyWidget)**

export default {
  name: 'SurveyJsVueTest',
  data () {
    return {
     ....
    }
  }
.....
`
In my Survey.JSON i declared a 'starrating' question but is not rendered properly.

I hope I have explained better my matter.

Thanks.

**Comment by tsv2013** [comment]
If I understand you right, you want to use SurveyJS custom widgets in a VueJS SPA application. We have a sample repo illustrating this - https://github.com/surveyjs/surveyjs_vue_quickstart

SurveyJS custom widgets are designed as a cross-framework vanilla-js objects, integrated with the SurveyJS library. It was done this way because we need to make widgets work across different frameworks - Angular, Knockout, jQuery, React and VueJS.
So naturally they are not VueJS components. Widgets are registered in a survey object in order to be used in a certain project.

**Comment by gongon2dotcom** [comment]
Thanks @tsv2013.
